name: CI Grader
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/thotypous/docker-fpga-builder:main'
    steps:
      - uses: actions/checkout@v2
      - name: Download and run grader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./run-grader
